language: python

env:
  - CODECOV_TOKEN="8c195e59-b68f-46f8-ac46-0c6b6100c336"

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements/requirements.txt
  # packages that wont be updated by pyup
  - pip install -r requirements/noupdate.txt
  - pip install -r requirements/postbuild.txt

script:
  - pylint --rcfile=.pylintrc multistream_select test
  - py.test --cov=multistream_select test/

after_success:
  - codecov
