language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements/requirements.txt
  # packages that wont be updated by pyup
  - pip install -r requirements/noupdate.txt

before_script:
  # run linter
  flake8 

script:
  py.test

after_success:
  py.test --cov=multistream_select test/