language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  # run linter
  flake8 

script:
  py.test

after_success:
  py.test --cov=multistream_select test/